export const USER_ACCOUNT = {
  SIGN_UP_REQUESTED: 'USER_SIGN_UP_REQUESTED',
  SIGN_UP_FAILED: 'USER_SIGN_UP_FAILED',
  SIGN_UP_SUCCESSFUL: 'USER_SIGN_UP_SUCCESSFUL',

  SIGN_IN_REQUESTED: 'USER_SIGN_IN_REQUESTED',
  SIGN_IN_FAILED: 'USER_SIGN_IN_FAILED',
  SIGN_IN_SUCCESSFUL: 'USER_SIGN_IN_SUCCESSFUL',

  SIGN_OUT_REQUESTED: 'USER_SIGN_OUT_REQUESTED',
  SIGN_OUT_FAILED: 'USER_SIGN_OUT_FAILED',
  SIGN_OUT_SUCCESSFUL: 'USER_SIGN_OUT_SUCCESSFUL',

  UPDATE_REQUESTED: 'USER_UPDATE_REQUESTED',
  UPDATE_FAILED: 'USER_UPDATE_FAILED',
  UPDATE_SUCCESSFUL: 'USER_UPDATE_SUCCESSFUL',

  DELETE_REQUESTED: 'USER_DELETE_REQUESTED',
  DELETE_FAILED: 'USER_DELETE_FAILED',
  DELETE_SUCCESSFUL: 'USER_DELETE_SUCCESSFUL',

  ADDRESS_UPDATE_REQUESTED: 'USER_ADDRESS_UPDATE_REQUESTED',
  ADDRESS_UPDATE_FAILED: 'USER_ADDRESS_UPDATE_FAILED',
  ADDRESS_UPDATE_SUCCESSFUL: 'USER_ADDRESS_UPDATE_SUCCESSFUL',
}

export const USERS = {
  LOAD_REQUESTED: 'USER_ACCOUNTS_REQUESTED',
  LOAD_FAILED: 'USER_ACCOUNTS_FAILED',
  LOAD_RECEIVED: 'USER_ACCOUNTS_RECEIVED',

  INFORMATION_REQUESTED: 'USER_INFORMATION_REQUESTED',
  INFORMATION_FAILED: 'USER_INFORMATION_FAILED',
  INFORMATION_SUCCESSFUL: 'USER_INFORMATION_SUCCESSFUL',
}
